
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Data_table = QtWidgets.QTableWidget(self.centralwidget)
        self.Data_table.setGeometry(QtCore.QRect(40, 170, 702, 212))
        self.Data_table.setShowGrid(True)
        self.Data_table.setWordWrap(True)
        self.Data_table.setCornerButtonEnabled(True)
        self.Data_table.setRowCount(7)
        self.Data_table.setColumnCount(7)
        self.Data_table.setObjectName("Data_table")
        self.Data_table.horizontalHeader().setVisible(False)
        self.Data_table.horizontalHeader().setHighlightSections(True)
        self.Data_table.verticalHeader().setVisible(False)
        self.Month_year = QtWidgets.QLabel(self.centralwidget)
        self.Month_year.setGeometry(QtCore.QRect(300, 120, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Month_year.setFont(font)
        self.Month_year.setAlignment(QtCore.Qt.AlignCenter)
        self.Month_year.setObjectName("Month_year")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/background_of_diary.jpg"))
        self.label.setObjectName("label")
        self.p2 = QtWidgets.QPushButton(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(140, 200, 101, 31))
        self.p2.setObjectName("p2")
        self.p3 = QtWidgets.QPushButton(self.centralwidget)
        self.p3.setGeometry(QtCore.QRect(240, 200, 101, 31))
        self.p3.setObjectName("p3")
        self.p4 = QtWidgets.QPushButton(self.centralwidget)
        self.p4.setGeometry(QtCore.QRect(340, 200, 101, 31))
        self.p4.setObjectName("p4")
        self.p5 = QtWidgets.QPushButton(self.centralwidget)
        self.p5.setGeometry(QtCore.QRect(440, 200, 101, 31))
        self.p5.setObjectName("p5")
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(40, 200, 101, 31))
        self.p1.setObjectName("p1")
        self.p6 = QtWidgets.QPushButton(self.centralwidget)
        self.p6.setGeometry(QtCore.QRect(540, 200, 101, 31))
        self.p6.setObjectName("p6")
        self.p7 = QtWidgets.QPushButton(self.centralwidget)
        self.p7.setGeometry(QtCore.QRect(640, 200, 101, 31))
        self.p7.setObjectName("p7")
        self.p8 = QtWidgets.QPushButton(self.centralwidget)
        self.p8.setGeometry(QtCore.QRect(40, 230, 101, 31))
        self.p8.setObjectName("p8")
        self.p9 = QtWidgets.QPushButton(self.centralwidget)
        self.p9.setGeometry(QtCore.QRect(140, 230, 101, 31))
        self.p9.setObjectName("p9")
        self.p10 = QtWidgets.QPushButton(self.centralwidget)
        self.p10.setGeometry(QtCore.QRect(240, 230, 101, 31))
        self.p10.setObjectName("p10")
        self.p11 = QtWidgets.QPushButton(self.centralwidget)
        self.p11.setGeometry(QtCore.QRect(340, 230, 101, 31))
        self.p11.setObjectName("p11")
        self.p12 = QtWidgets.QPushButton(self.centralwidget)
        self.p12.setGeometry(QtCore.QRect(440, 230, 101, 31))
        self.p12.setObjectName("p12")
        self.p13 = QtWidgets.QPushButton(self.centralwidget)
        self.p13.setGeometry(QtCore.QRect(540, 230, 101, 31))
        self.p13.setObjectName("p13")
        self.p14 = QtWidgets.QPushButton(self.centralwidget)
        self.p14.setGeometry(QtCore.QRect(640, 230, 101, 31))
        self.p14.setObjectName("p14")
        self.p21 = QtWidgets.QPushButton(self.centralwidget)
        self.p21.setGeometry(QtCore.QRect(640, 260, 101, 31))
        self.p21.setObjectName("p21")
        self.p28 = QtWidgets.QPushButton(self.centralwidget)
        self.p28.setGeometry(QtCore.QRect(640, 290, 101, 31))
        self.p28.setObjectName("p28")
        self.p35 = QtWidgets.QPushButton(self.centralwidget)
        self.p35.setGeometry(QtCore.QRect(640, 320, 101, 31))
        self.p35.setObjectName("p35")
        self.p20 = QtWidgets.QPushButton(self.centralwidget)
        self.p20.setGeometry(QtCore.QRect(540, 260, 101, 31))
        self.p20.setObjectName("p20")
        self.p27 = QtWidgets.QPushButton(self.centralwidget)
        self.p27.setGeometry(QtCore.QRect(540, 290, 101, 31))
        self.p27.setObjectName("p27")
        self.p34 = QtWidgets.QPushButton(self.centralwidget)
        self.p34.setGeometry(QtCore.QRect(540, 320, 101, 31))
        self.p34.setObjectName("p34")
        self.p19 = QtWidgets.QPushButton(self.centralwidget)
        self.p19.setGeometry(QtCore.QRect(440, 260, 101, 31))
        self.p19.setObjectName("p19")
        self.p26 = QtWidgets.QPushButton(self.centralwidget)
        self.p26.setGeometry(QtCore.QRect(440, 290, 101, 31))
        self.p26.setObjectName("p26")
        self.p33 = QtWidgets.QPushButton(self.centralwidget)
        self.p33.setGeometry(QtCore.QRect(440, 320, 101, 31))
        self.p33.setObjectName("p33")
        self.p18 = QtWidgets.QPushButton(self.centralwidget)
        self.p18.setGeometry(QtCore.QRect(340, 260, 101, 31))
        self.p18.setObjectName("p18")
        self.p25 = QtWidgets.QPushButton(self.centralwidget)
        self.p25.setGeometry(QtCore.QRect(340, 290, 101, 31))
        self.p25.setObjectName("p25")
        self.p32 = QtWidgets.QPushButton(self.centralwidget)
        self.p32.setGeometry(QtCore.QRect(340, 320, 101, 31))
        self.p32.setObjectName("p32")
        self.p17 = QtWidgets.QPushButton(self.centralwidget)
        self.p17.setGeometry(QtCore.QRect(240, 260, 101, 31))
        self.p17.setObjectName("p17")
        self.p24 = QtWidgets.QPushButton(self.centralwidget)
        self.p24.setGeometry(QtCore.QRect(240, 290, 101, 31))
        self.p24.setObjectName("p24")
        self.p31 = QtWidgets.QPushButton(self.centralwidget)
        self.p31.setGeometry(QtCore.QRect(240, 320, 101, 31))
        self.p31.setObjectName("p31")
        self.p16 = QtWidgets.QPushButton(self.centralwidget)
        self.p16.setGeometry(QtCore.QRect(140, 260, 101, 31))
        self.p16.setObjectName("p16")
        self.p23 = QtWidgets.QPushButton(self.centralwidget)
        self.p23.setGeometry(QtCore.QRect(140, 290, 101, 31))
        self.p23.setObjectName("p23")
        self.p30 = QtWidgets.QPushButton(self.centralwidget)
        self.p30.setGeometry(QtCore.QRect(140, 320, 101, 31))
        self.p30.setObjectName("p30")
        self.p22 = QtWidgets.QPushButton(self.centralwidget)
        self.p22.setGeometry(QtCore.QRect(40, 290, 101, 31))
        self.p22.setObjectName("p22")
        self.p29 = QtWidgets.QPushButton(self.centralwidget)
        self.p29.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.p29.setObjectName("p29")
        self.p15 = QtWidgets.QPushButton(self.centralwidget)
        self.p15.setGeometry(QtCore.QRect(40, 260, 101, 31))
        self.p15.setObjectName("p15")
        self.Monday = QtWidgets.QLabel(self.centralwidget)
        self.Monday.setGeometry(QtCore.QRect(40, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Monday.setFont(font)
        self.Monday.setAlignment(QtCore.Qt.AlignCenter)
        self.Monday.setObjectName("Monday")
        self.Tuesday = QtWidgets.QLabel(self.centralwidget)
        self.Tuesday.setGeometry(QtCore.QRect(140, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Tuesday.setFont(font)
        self.Tuesday.setAlignment(QtCore.Qt.AlignCenter)
        self.Tuesday.setObjectName("Tuesday")
        self.Wednesday = QtWidgets.QLabel(self.centralwidget)
        self.Wednesday.setGeometry(QtCore.QRect(240, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Wednesday.setFont(font)
        self.Wednesday.setAlignment(QtCore.Qt.AlignCenter)
        self.Wednesday.setObjectName("Wednesday")
        self.Thursday = QtWidgets.QLabel(self.centralwidget)
        self.Thursday.setGeometry(QtCore.QRect(340, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Thursday.setFont(font)
        self.Thursday.setAlignment(QtCore.Qt.AlignCenter)
        self.Thursday.setObjectName("Thursday")
        self.Friday = QtWidgets.QLabel(self.centralwidget)
        self.Friday.setGeometry(QtCore.QRect(440, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Friday.setFont(font)
        self.Friday.setAlignment(QtCore.Qt.AlignCenter)
        self.Friday.setObjectName("Friday")
        self.Saturday = QtWidgets.QLabel(self.centralwidget)
        self.Saturday.setGeometry(QtCore.QRect(540, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Saturday.setFont(font)
        self.Saturday.setAlignment(QtCore.Qt.AlignCenter)
        self.Saturday.setObjectName("Saturday")
        self.Sunday = QtWidgets.QLabel(self.centralwidget)
        self.Sunday.setGeometry(QtCore.QRect(640, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sunday.setFont(font)
        self.Sunday.setAlignment(QtCore.Qt.AlignCenter)
        self.Sunday.setObjectName("Sunday")
        self.p42 = QtWidgets.QPushButton(self.centralwidget)
        self.p42.setGeometry(QtCore.QRect(640, 350, 101, 31))
        self.p42.setObjectName("p42")
        self.p41 = QtWidgets.QPushButton(self.centralwidget)
        self.p41.setGeometry(QtCore.QRect(540, 350, 101, 31))
        self.p41.setObjectName("p41")
        self.p40 = QtWidgets.QPushButton(self.centralwidget)
        self.p40.setGeometry(QtCore.QRect(440, 350, 101, 31))
        self.p40.setObjectName("p40")
        self.p39 = QtWidgets.QPushButton(self.centralwidget)
        self.p39.setGeometry(QtCore.QRect(340, 350, 101, 31))
        self.p39.setObjectName("p39")
        self.p38 = QtWidgets.QPushButton(self.centralwidget)
        self.p38.setGeometry(QtCore.QRect(240, 350, 101, 31))
        self.p38.setObjectName("p38")
        self.p37 = QtWidgets.QPushButton(self.centralwidget)
        self.p37.setGeometry(QtCore.QRect(140, 350, 101, 31))
        self.p37.setObjectName("p37")
        self.p36 = QtWidgets.QPushButton(self.centralwidget)
        self.p36.setGeometry(QtCore.QRect(40, 350, 101, 31))
        self.p36.setObjectName("p36")
        self.label.raise_()
        self.Data_table.raise_()
        self.Month_year.raise_()
        self.p2.raise_()
        self.p3.raise_()
        self.p4.raise_()
        self.p5.raise_()
        self.p1.raise_()
        self.p6.raise_()
        self.p7.raise_()
        self.p8.raise_()
        self.p9.raise_()
        self.p10.raise_()
        self.p11.raise_()
        self.p12.raise_()
        self.p13.raise_()
        self.p14.raise_()
        self.p21.raise_()
        self.p28.raise_()
        self.p35.raise_()
        self.p20.raise_()
        self.p27.raise_()
        self.p34.raise_()
        self.p19.raise_()
        self.p26.raise_()
        self.p33.raise_()
        self.p18.raise_()
        self.p25.raise_()
        self.p32.raise_()
        self.p17.raise_()
        self.p24.raise_()
        self.p31.raise_()
        self.p16.raise_()
        self.p23.raise_()
        self.p30.raise_()
        self.p22.raise_()
        self.p29.raise_()
        self.p15.raise_()
        self.Monday.raise_()
        self.Tuesday.raise_()
        self.Wednesday.raise_()
        self.Thursday.raise_()
        self.Friday.raise_()
        self.Saturday.raise_()
        self.Sunday.raise_()
        self.p42.raise_()
        self.p41.raise_()
        self.p40.raise_()
        self.p39.raise_()
        self.p38.raise_()
        self.p37.raise_()
        self.p36.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuBackground = QtWidgets.QMenu(self.menuSettings)
        self.menuBackground.setObjectName("menuBackground")
        self.menuTypescreen = QtWidgets.QMenu(self.menuSettings)
        self.menuTypescreen.setObjectName("menuTypescreen")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionScreen_resolution = QtWidgets.QAction(MainWindow)
        self.actionScreen_resolution.setObjectName("actionScreen_resolution")
        self.actionDarkside = QtWidgets.QAction(MainWindow)
        self.actionDarkside.setObjectName("actionDarkside")
        self.actionWhiteside = QtWidgets.QAction(MainWindow)
        self.actionWhiteside.setObjectName("actionWhiteside")
        self.actionColorful_side = QtWidgets.QAction(MainWindow)
        self.actionColorful_side.setObjectName("actionColorful_side")
        self.actionYour_side = QtWidgets.QAction(MainWindow)
        self.actionYour_side.setObjectName("actionYour_side")
        self.actionNormal = QtWidgets.QAction(MainWindow)
        self.actionNormal.setObjectName("actionNormal")
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setObjectName("actionBold")
        self.menuBackground.addAction(self.actionDarkside)
        self.menuBackground.addAction(self.actionWhiteside)
        self.menuBackground.addAction(self.actionColorful_side)
        self.menuBackground.addAction(self.actionYour_side)
        self.menuTypescreen.addAction(self.actionNormal)
        self.menuTypescreen.addAction(self.actionBold)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuBackground.menuAction())
        self.menuSettings.addAction(self.actionScreen_resolution)
        self.menuSettings.addAction(self.menuTypescreen.menuAction())
        self.menuSettings.addAction(self.actionExit)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diary"))
        self.Month_year.setText(_translate("MainWindow", "Month and year"))
        self.p2.setText(_translate("MainWindow", "PushButton"))
        self.p3.setText(_translate("MainWindow", "PushButton"))
        self.p4.setText(_translate("MainWindow", "PushButton"))
        self.p5.setText(_translate("MainWindow", "PushButton"))
        self.p1.setText(_translate("MainWindow", "PushButton"))
        self.p6.setText(_translate("MainWindow", "PushButton"))
        self.p7.setText(_translate("MainWindow", "PushButton"))
        self.p8.setText(_translate("MainWindow", "PushButton"))
        self.p9.setText(_translate("MainWindow", "PushButton"))
        self.p10.setText(_translate("MainWindow", "PushButton"))
        self.p11.setText(_translate("MainWindow", "PushButton"))
        self.p12.setText(_translate("MainWindow", "PushButton"))
        self.p13.setText(_translate("MainWindow", "PushButton"))
        self.p14.setText(_translate("MainWindow", "PushButton"))
        self.p21.setText(_translate("MainWindow", "PushButton"))
        self.p28.setText(_translate("MainWindow", "PushButton"))
        self.p35.setText(_translate("MainWindow", "PushButton"))
        self.p20.setText(_translate("MainWindow", "PushButton"))
        self.p27.setText(_translate("MainWindow", "PushButton"))
        self.p34.setText(_translate("MainWindow", "PushButton"))
        self.p19.setText(_translate("MainWindow", "PushButton"))
        self.p26.setText(_translate("MainWindow", "PushButton"))
        self.p33.setText(_translate("MainWindow", "PushButton"))
        self.p18.setText(_translate("MainWindow", "PushButton"))
        self.p25.setText(_translate("MainWindow", "PushButton"))
        self.p32.setText(_translate("MainWindow", "PushButton"))
        self.p17.setText(_translate("MainWindow", "PushButton"))
        self.p24.setText(_translate("MainWindow", "PushButton"))
        self.p31.setText(_translate("MainWindow", "PushButton"))
        self.p16.setText(_translate("MainWindow", "PushButton"))
        self.p23.setText(_translate("MainWindow", "PushButton"))
        self.p30.setText(_translate("MainWindow", "PushButton"))
        self.p22.setText(_translate("MainWindow", "PushButton"))
        self.p29.setText(_translate("MainWindow", "PushButton"))
        self.p15.setText(_translate("MainWindow", "PushButton"))
        self.Monday.setText(_translate("MainWindow", "Пн"))
        self.Tuesday.setText(_translate("MainWindow", "Вт"))
        self.Wednesday.setText(_translate("MainWindow", "Ср"))
        self.Thursday.setText(_translate("MainWindow", "Чт"))
        self.Friday.setText(_translate("MainWindow", "Пт"))
        self.Saturday.setText(_translate("MainWindow", "Сб"))
        self.Sunday.setText(_translate("MainWindow", "Вс"))
        self.p42.setText(_translate("MainWindow", "PushButton"))
        self.p41.setText(_translate("MainWindow", "PushButton"))
        self.p40.setText(_translate("MainWindow", "PushButton"))
        self.p39.setText(_translate("MainWindow", "PushButton"))
        self.p38.setText(_translate("MainWindow", "PushButton"))
        self.p37.setText(_translate("MainWindow", "PushButton"))
        self.p36.setText(_translate("MainWindow", "PushButton"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuBackground.setTitle(_translate("MainWindow", "Background"))
        self.menuTypescreen.setTitle(_translate("MainWindow", "Typescreen"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionScreen_resolution.setText(_translate("MainWindow", "Screen resolution"))
        self.actionDarkside.setText(_translate("MainWindow", "Darkside"))
        self.actionWhiteside.setText(_translate("MainWindow", "White side"))
        self.actionColorful_side.setText(_translate("MainWindow", "Colorful side"))
        self.actionYour_side.setText(_translate("MainWindow", "Your side"))
        self.actionNormal.setText(_translate("MainWindow", "Normal"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
